# name: appwithfirebase
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: ^3.10.7

# dependencies:
#   flutter:
#     sdk: flutter
#   firebase_core: ^3.0.0 # Standard stable version
#   firebase_auth: ^5.0.0
#   cloud_firestore: ^5.0.0
#   flutter_svg: ^2.0.10
#   awesome_dialog: ^3.3.0
#   flutter_screenutil: ^5.9.3
#   flutter_bloc: ^9.1.1
#   flutter_launcher_icons: ^0.14.4
  
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   # Downgraded to a version that currently exists
#   flutter_lints: ^4.0.0 

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/  # This is okay for images

#   fonts:
#     - family: SFCompactDisplay
#       fonts:
#         # DO NOT put "- assets/fonts/" here. 
#         # You must list the specific files:
#         - asset: assets/fonts/FontsFree-Net-SFCompactDisplay-Bold.ttf
#         - asset: assets/fonts/SF-Compact-Display-Semibold.ttf



name: appwithfirebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_svg: ^2.0.10
  awesome_dialog: ^3.3.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  persistent_bottom_nav_bar: ^6.2.1
  flutter_easy_multi_step_form: ^1.0.5
  url_launcher: ^6.2.6
  file_picker: ^11.0.1
  firebase_storage: ^12.4.10
  syncfusion_flutter_pdfviewer: 26.2.14
  device_info_plus: 10.1.2
  # syncfusion_flutter_pdfviewer: ^33.1.46

  bloc: ^9.2.0
  image_picker: ^1.2.1
  http: ^1.6.0
  path_provider: ^2.1.5
  flutter_media_downloader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFCompactDisplay
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFCompactDisplay-Bold.ttf
        - asset: assets/fonts/SF-Compact-Display-Semibold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"