// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcQd2XPmsNyW19wwFQq79MdOPdtanFwc',
    appId: '1:811565825223:web:a9cb6856b80f02f1ce12e2',
    messagingSenderId: '811565825223',
    projectId: 'appwithfirebase-2abba',
    authDomain: 'appwithfirebase-2abba.firebaseapp.com',
    storageBucket: 'appwithfirebase-2abba.firebasestorage.app',
    measurementId: 'G-GVQJKFMFN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGbzWHDnfeJPTiAY2zHDLQHp-n1OVSkCU',
    appId: '1:811565825223:android:a45f4e13911358a2ce12e2',
    messagingSenderId: '811565825223',
    projectId: 'appwithfirebase-2abba',
    storageBucket: 'appwithfirebase-2abba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4aF8ixewU9RuRwHAmzpkGO754yb9LoJ8',
    appId: '1:811565825223:ios:0529d27530ac0f6bce12e2',
    messagingSenderId: '811565825223',
    projectId: 'appwithfirebase-2abba',
    storageBucket: 'appwithfirebase-2abba.firebasestorage.app',
    iosBundleId: 'com.example.appwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4aF8ixewU9RuRwHAmzpkGO754yb9LoJ8',
    appId: '1:811565825223:ios:0529d27530ac0f6bce12e2',
    messagingSenderId: '811565825223',
    projectId: 'appwithfirebase-2abba',
    storageBucket: 'appwithfirebase-2abba.firebasestorage.app',
    iosBundleId: 'com.example.appwithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWcQd2XPmsNyW19wwFQq79MdOPdtanFwc',
    appId: '1:811565825223:web:6f58aee32c47fa25ce12e2',
    messagingSenderId: '811565825223',
    projectId: 'appwithfirebase-2abba',
    authDomain: 'appwithfirebase-2abba.firebaseapp.com',
    storageBucket: 'appwithfirebase-2abba.firebasestorage.app',
    measurementId: 'G-Z5GQZTY5Q9',
  );
}
